### ISSUE TITLE
subscribeToGuildEvents / AttributeError: 'guild' object has no attribute 'position'

### ISSUE THREAD

**Issue by reapski** [Merubokkusu/Discord-S.C.U.M#118]
tried everything to resolve this. still no idea. 

gateway is running and connected; worked fine in 1.3.0 afaik. 

tried a few accounts and a few different setups, even ran the example jic but no luck.
_______________________
arandomnewaccount:
hey, thanks for bringing this up. Fixed it in this commit: https://github.com/Merubokkusu/Discord-S.C.U.M/commit/12182d2bf199b4db21e4e543f49a02c6dfe6a169

edit: closing this as answered
